config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    resources :people
  end

  namespace :api do
    namespace :v1 do
      resources :people, only: [:index, :show, :create] do
        resource :detail, only: [:show, :create]
      end
    end
  end

  # Defines the root path route ("/")
  root "admin/people#index"
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    "admin_"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/detail.rb
class Detail < ApplicationRecord
  TITLE = ['Dr.', 'Mr.', 'Mrs.', 'Prof.'].freeze
  #-------------------------------------------------------------------------------------
  # Associations
  #-------------------------------------------------------------------------------------
  belongs_to :person

  #-------------------------------------------------------------------------------------
  # Validations
  #-------------------------------------------------------------------------------------
  validates :email, presence: true
  validates :email, uniqueness: true, format: { with: ::URI::MailTo::EMAIL_REGEXP }, allow_blank: true
end

app/models/person.rb
class Person < ApplicationRecord
  #-------------------------------------------------------------------------------------
  # Associations
  #-------------------------------------------------------------------------------------
  has_one :detail, dependent: :destroy

  #-------------------------------------------------------------------------------------
  # Validations
  #-------------------------------------------------------------------------------------
  validates :name, presence: true

  accepts_nested_attributes_for :detail, reject_if: :all_blank
end

app/controllers/admin/people_controller.rb
class Admin::PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /admin/people
  def index
    @people = Person.all
  end

  # GET /admin/people/:id
  def show
    @detail = @person.detail
  end

  # GET /admin/people/new
  def new
    @person = Person.new
    @person.build_detail
  end

  # GET /admin/people/:id/edit
  def edit
  end

  # POST /admin/people
  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to admin_person_path(@person), notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /admin/people/1
  def update
    if @person.update(person_params)
      redirect_to admin_person_path(@person), notice: t('.success'), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /admin/people/1
  def destroy
    @person.destroy!
    redirect_to admin_people_url, notice: t('.success'), status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find_by(id: params[:id])

      if @person.blank?
        flash.notice = t('.not_found', id: params[:id])
        redirect_to admin_people_path
      end
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, detail_attributes: [:title, :age, :email, :phone])
    end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ::ApplicationController
    protect_from_forgery with: :null_session
  end
end

app/controllers/api/v1/details_controller.rb
module Api
  module V1
    class DetailsController < ::Api::ApiController
      before_action :set_person

      # GET /api/v1/people/:person_id/detail
      def show
        render json: (@person.detail || {})
      end

      # POST /api/v1/people/:person_id/detail
      def create
        @person.update(detail_attributes: permitted_params)

        if @person.errors.blank?
          render json: @person.detail
        else
          render json: { error: @person.errors.full_messages.to_sentence }, status: :unprocessable_entity
        end
      end

      private def set_person
        @person = ::Person.find_by(id: params[:person_id])

        if @person.blank?
          render json: { error: t('api.v1.people.not_found', id: params[:person_id]) }, status: :not_found
        end
      end

      private def permitted_params
        params.permit(:age, :email, :phone, :title)
      end
    end
  end
end

app/controllers/api/v1/people_controller.rb
module Api
  module V1
    class PeopleController < ::Api::ApiController
      before_action :set_person, only: :show

      RESULT_PER_PAGE = 25

      # GET /api/v1/people
      def index
        page_no = params[:page].to_i || 1
        offset = (page_no - 1) * RESULT_PER_PAGE
        @people = ::Person.limit(RESULT_PER_PAGE).offset(offset)

        render json: @people
      end

      # GET /api/v1/people/:id
      def show
        render json: @person
      end

      # POST /api/v1/people
      def create
        @person = ::Person.new(permitted_params)

        if @person.save
          render json: @person
        else
          render json: { error: @person.errors.full_messages.to_sentence }, status: :unprocessable_entity
        end
      end

      private def set_person
        @person = ::Person.find_by(id: params[:id])

        if @person.blank?
          render json: { error: t('.not_found', id: params[:id]) }, status: :not_found
        end
      end

      private def permitted_params
        params.permit(:name)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/people_helper.rb
module Admin::PeopleHelper
  def name_with_title(person)
    "#{person.detail&.title} #{person.name}".strip
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/people/_form.html.erb
<%= form_with(model: [:admin, person]) do |form| %>
  <% if person.errors.any? %>
    <div class="error">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.fields_for :detail do |detail_form| %>
      <div>
        <%= form.label :title %>
        <%= detail_form.select :title, ::Detail::TITLE.collect { |title| [title, title] } %>
      </div>
      <div>
        <%= form.label :age %>
        <%= detail_form.number_field :age %>
      </div>
      <div>
        <%= form.label :email %>
        <%= detail_form.email_field :email, required: true %>
      </div>
      <div>
        <%= form.label :phone %>
        <%= detail_form.phone_field :phone %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <%= link_to person.name, admin_person_path(person), data: { "turbo-frame": 'person_details' } %>
  </p>

</div>

app/views/admin/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", admin_person_path(@person) %> |
  <%= link_to "Back to people", admin_people_path %>
</div>

app/views/admin/people/index.html.erb
<p class="notice"><%= notice %></p>

<%= link_to "New person", new_admin_person_path %>
<h1>People</h1>

<div class='people-container'>
  <div id="admin_people" class='people-list'>
    <% @people.each do |person| %>
      <%= render person %>
    <% end %>
  </div>
  <div>
    <%= turbo_frame_tag 'person_details' do %>
    <% end %>
  </div>
</div>

app/views/admin/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", admin_people_path %>
</div>

app/views/admin/people/show.html.erb
<p class="notice"><%= notice %></p>

<div> <%= link_to "Back to people", admin_people_path %> </div>

<%= turbo_frame_tag 'person_details' do %>
  <div class="people-info">
    <h1> <%= name_with_title(@person) %> </h1>
    <% if @detail.present? %>
      <p> email: <%= @detail.email %> </p>
      <p> age: <%= @detail.age %> </p>
      <p> phone: <%= @detail.phone %> </p>
    <% end %>

    <%= link_to "Edit this person", edit_admin_person_path(@person), data: { turbo: false } %>

    <%= button_to "Destroy this person", admin_person_path(@person), method: :delete, data: { turbo: false } %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketcircleAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>